### ISSUE TITLE
AAU OneDay site throws errors

### ISSUE THREAD

**Issue by falkecarlsen** [cogitantium/chwifi#29]
Might just be a temporary bug or seasonal, as summer break is in effect.

chwifi throws this error but correctly identifies the update as failed:
```
/tmp/chwifi-passwords.html:6: HTML parser error : Unexpected end tag : meta
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
                                                                              ^
XPath set is empty
Failed to update cached passwords!
```

AAU OneDay throws this 500 error upon logging in:
```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/srv/web/AauWifi/aauwifi/lib/fast/cas/cas.py", line 64, in wrapper
    return func(*args, **kwargs)
  File "/srv/web/AauWifi/aauwifi/aauwifi.py", line 177, in oneday
    db = fast.db3.FastDB(psycopg2.connect(**cherrypy.config['dbinfo']))
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db1.adm.es.aau.dk" (130.225.51.117) and accepting
	TCP/IP connections on port 5432?

Powered by CherryPy 3.5.0 
```
This should probably be handled better, somehow identifying whether the site is functioning properly instead of failing on unexpected input.

**Comment by falkecarlsen** [comment]
Note that connection is still handled fine, only the password update routine is broken.

**Comment by falkecarlsen** [comment]
AAU OneDay is now up again after AAU IT has fixed their network errors, and chwifi again works as intended.

Opened #30 to reflect findings.
